# SPDX-License-Identifier: Apache-2.0

execute_process(
  COMMAND "git" "rev-parse" "--short" "HEAD"
  WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
  OUTPUT_VARIABLE GIT_COMMIT
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_QUIET
)

set(CONFIGURE_COMMAND "cmake -DBTOP_GPU=${BTOP_GPU} -DBTOP_STATIC=${BTOP_STATIC}")

get_filename_component(COMPILER "${CMAKE_CXX_COMPILER}" NAME)
set(COMPILER_VERSION "${CMAKE_CXX_COMPILER_VERSION}")
