# SPDX-License-Identifier: Apache-2.0

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_COMMIT
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)

cmake_path(GET CMAKE_CXX_COMPILER FILENAME COMPILER)
set(COMPILER_VERSION ${CMAKE_CXX_COMPILER_VERSION})
set(CONFIGURE_COMMAND "cmake")
