name: btop
title: btop++
contact: https://github.com/aristocratos/btop/issues
issues: https://github.com/aristocratos/btop/issues
donation:
  - https://github.com/sponsors/aristocratos
  - https://ko-fi.com/aristocratos
  - https://www.paypal.com/paypalme/aristocratos
source-code: https://github.com/aristocratos/btop
website: https://github.com/aristocratos/btop
adopt-info: btop
summary: Resource monitor that shows usage and stats
description: |
  Resource monitor that shows usage and stats for processor, memory, disks, network and processes.
  C++ version and continuation of bashtop and bpytop.
license: Apache-2.0

base: core22
grade: stable
confinement: strict
compression: lzo

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x

package-repositories:
  - type: apt
    ppa: ubuntu-toolchain-r/test

apps:
  btop:
    command: usr/local/bin/btop
    desktop: usr/local/share/applications/btop.desktop
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    plugs:
      - mount-observe
      - process-control
      - system-observe
      - hardware-observe
      - network
      - network-observe
      - home
      - removable-media
      - opengl

parts:
  btop:
    source: https://github.com/aristocratos/btop
    source-type: git
    plugin: make
    make-parameters:
      - CXX=g++-11
      - PREFIX=/usr/local
      - STATIC=true
      - ADDFLAGS="-D SNAPPED"
    # Add 'lowdown' to build dependencies as soon at Snap builder updates from
    # Ubuntu 20.04 "Focal" to something newer that has Lowdown included
    build-packages:
      - coreutils
      - sed
      - git
      - build-essential
      - gcc-11
      - g++-11

    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"

    override-build: |
      craftctl default

      # Patch icon path of the desktop entry
      # WORKAROUND: Use PNG icon until KDE Plasma can correctly render the SVG one
      # Bug: https://bugs.kde.org/show_bug.cgi?id=448234
      sed -i 's|Icon=btop|Icon=/usr/local/share/icons/hicolor/48x48/apps/btop.png|' "${CRAFT_PART_INSTALL}/usr/local/share/applications/btop.desktop"
