name: OpenBSD CMake

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: main
    tags-ignore: '*.*'
    paths:
      - '.github/workflows/cmake-openbsd.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'include/**'
      - 'src/*pp'
      - 'src/openbsd/*pp'
      - 'tests/**'
  pull_request:
    branches: main
    paths:
      - '.github/workflows/cmake-openbsd.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'include/**'
      - 'src/*pp'
      - 'src/openbsd/*pp'
      - 'tests/**'

jobs:
  build:
    name: openbsd-${{ matrix.version}}-${{ matrix.arch}}
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.arch }}-${{ matrix.version }}
      cancel-in-progress: true
    strategy:
      matrix:
        arch: ['aarch64', 'x86_64']
        version: ['7.9']
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Compile
        uses: vmactions/openbsd-vm@18edb32f4e48dae5865d7b8b3a9587bc01218a20 # v1.4.4
        with:
          arch: ${{ matrix.arch }}
          release: ${{ matrix.version }}
          usesh: true
          prepare: pkg_add cmake git ninja
          run: |
            cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
            cmake --build build --verbose
            ctest --test-dir build
