name: FreeBSD CMake

permissions: {}

on:
  workflow_dispatch:
  push:
    branches: main
    tags-ignore: '*.*'
    paths:
      - '.github/workflows/cmake-freebsd.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'include/**'
      - 'src/*pp'
      - 'src/freebsd/*pp'
      - 'tests/**'
  pull_request:
    branches: main
    paths:
      - '.github/workflows/cmake-freebsd.yml'
      - 'CMakeLists.txt'
      - 'cmake/**'
      - 'include/**'
      - 'src/*pp'
      - 'src/freebsd/*pp'
      - 'tests/**'

jobs:
  build:
    name: freebsd-${{ matrix.version}}-${{ matrix.arch}}
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.arch }}-${{ matrix.version }}
      cancel-in-progress: true
    strategy:
      matrix:
        arch: ['aarch64', 'x86_64']
        version: ['14.4', '15.1']
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Compile
        uses: vmactions/freebsd-vm@5a72679103d223925653750faa878a143340fbd0 # v1.5.0
        with:
          arch: ${{ matrix.arch }}
          release: ${{ matrix.version }}
          usesh: true
          prepare: pkg install -y cmake git ninja
          run: |
            cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug
            cmake --build build --verbose
            ctest --test-dir build
