name: Continuous Build Linux

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - "*.*"
    paths:
      - "src/**"
      - "!src/osx/**"
      - "!src/freebsd/**"
      - "!src/netbsd/**"
      - "!src/openbsd/**"
      - "include/**"
      - "Makefile"
      - ".github/workflows/continuous-build-linux.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "!src/osx/**"
      - "!src/freebsd/**"
      - "!src/netbsd/**"
      - "!src/openbsd/**"
      - "include/**"
      - "Makefile"
      - ".github/workflows/continuous-build-linux.yml"

jobs:
  build:
    runs-on: ubuntu-24.04
    container: ubuntu:25.04
    continue-on-error: true
    strategy:
      matrix:
        include:
          - triple: aarch64
          - triple: alpha
          - triple: arc
          - triple: arm
            abi: eabi
          - triple: arm
            abi: eabihf
          - triple: hppa
          - triple: i686
          - triple: loongarch64
          - triple: m68k
          - triple: powerpc
          - triple: powerpc64
          - triple: powerpc64le
          - triple: riscv64
          - triple: s390x
          - triple: sh4
          - triple: sparc64
          - triple: x86-64
            xtriple: x86_64
          - triple: x86-64
            xtriple: x86_64
            abi: x32

    steps:
      - uses: actions/checkout@v5

      - name: Install build tools
        run: |
          apt-get update
          apt-get install -y --no-install-recommends make \
            ${{ matrix.triple == 'x86-64' && 'binutils' || '' }} \
            g++-15-${{ matrix.triple }}-linux-gnu${{ matrix.abi || '' }}

      - name: Compile
        run: CXX=${{ matrix.xtriple || matrix.triple }}-linux-gnu${{ matrix.abi || '' }}-g++-15 make STATIC=true STRIP=true VERBOSE=true
