name: Make Linux 🐧

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags-ignore:
      - '*.*'
    paths:
      - 'src/**'
      - '!src/osx/**'
      - '!src/freebsd/**'
      - '!src/netbsd/**'
      - '!src/openbsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/continuous-build-linux.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '!src/osx/**'
      - '!src/freebsd/**'
      - '!src/netbsd/**'
      - '!src/openbsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/continuous-build-linux.yml'

jobs:
  build:
    name: Build 🔨
    runs-on: ubuntu-24.04
    container: dockcross/${{ matrix.toolchain }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ matrix.toolchain }}
      cancel-in-progress: true
    strategy:
      matrix:
        toolchain:
          - linux-arm64
          - linux-mips
          - linux-s390x
          - linux-ppc64le
          - linux-riscv64
          - linux-x64
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make STATIC=true STRIP=true
