name: 🧪 Test snap can be built on x86_64

permissions: {}

on:
  workflow_dispatch:
  push:
   branches: [ main ]
   tags-ignore:
      - '*.*'
   paths:
      - 'src/**'
      - '!src/osx/**'
      - '!src/freebsd/**'
      - '!src/netbsd/**'
      - '!src/openbsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/test-snap-can-build.yml'
      - 'snap/snapcraft.yaml'
  pull_request:
   branches: [ main ]
   paths:
      - 'src/**'
      - '!src/osx/**'
      - '!src/freebsd/**'
      - '!src/netbsd/**'
      - '!src/openbsd/**'
      - 'include/**'
      - 'Makefile'
      - '.github/workflows/test-snap-can-build.yml'
      - 'snap/snapcraft.yaml'

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: snapcore/action-build@3bdaa03e1ba6bf59a65f84a751d943d549a54e79 # v1.3.0
        id: build

      - uses: diddlesnaps/snapcraft-review-action@40554b42331cf84dab19ef98c382620427f13482 # v1.3.1
        with:
          snap: ${{ steps.build.outputs.snap }}
          isClassic: 'false'
